<?php
/**
 * Created by PhpStorm.
 * User: markopoikkimaki
 * Date: 2018-12-01
 * Time: 13:38
 */

namespace App\Command;


use App\Service\Greeting;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class HelloCommand extends Command
{
    /**
     * @var Greeting
     */
    private $greeting;

    /**
     * HelloCommand constructor.
     */
    public function __construct(Greeting $greeting)
    {
        $this->greeting = $greeting;

        parent::__construct();

    }

    protected function configure()
    {

        $this->setName('app:say-hello')
             ->setDescription('Says hello to the user')
             ->addArgument('name', InputArgument::REQUIRED);

    //    parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
         $name = $input->getArgument('name');
         $output->writeln(['HELLO FROM THE APP!!!! ', '=================', ':)']);
         $msg = $this->greeting->greet($name);
         $output->writeln($msg);

      //  parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}