<?php
/**
 * Created by PhpStorm.
 * User: markopoikkimaki
 * Date: 2018-12-01
 * Time: 13:38
 */

namespace App\Command;


use App\Repository\HelloRepository;
use App\Entity\Hello;
use App\Service\Greeting;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\ORM\EntityManagerInterface;

class HelloCommand extends Command
{
    /**
     * @var Greeting
     */
    private $greeting;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;


    /**
     * HelloCommand constructor.
     */
    public function __construct(Greeting $greeting, EntityManagerInterface $entityManager)
    {
        parent::__construct();

        $this->greeting = $greeting;

        $this->entityManager = $entityManager;
    }

    protected function configure()
    {

        $this->setName('app:say-hello')
             ->setDescription('Says hello to the user');

        //     ->addArgument('name', InputArgument::REQUIRED);

    //    parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        /*
         $name = $input->getArgument('name');
         $output->writeln(['HELLO FROM THE APP!!!! ', '=================', ':)']);
         $msg = $this->greeting->greet($name);
         $output->writeln($msg);
         */
         //  parent::execute($input, $output); // TODO: Change the autogenerated stub

        $hello = new Hello();
        $hello->setGreeting('Hello World!');
        $hello->setDate(new \DateTime());

        $this->entityManager->persist($hello);
        $this->entityManager->flush();

    }


}